### ISSUE TITLE
Framework pages style issue

### ISSUE THREAD

**Issue by PraveenPal4232** [GoogleChromeLabs/perf-track#16]
Hi @housseindjirdeh
Right Now all framework pages have a minor style issue.
It seems like it is a container height problem. The little footer is also massing up because of this.

![minor style issue)](https://user-images.githubusercontent.com/34737190/87158256-12f79d80-c2dd-11ea-8383-71ba9ff63fb4.png)

Thanks :)

**Comment by housseindjirdeh** [comment]
Thanks for logging this @PraveenPal4232 :)

So this _should_ have been resolved by #, but I most probably fiddled around with the container heights after that causing it to overflow on certain screens 😅
