### ISSUE TITLE
Pie chart doesn't reflect listed percentages for "compressed requests"

### ISSUE THREAD

**Issue by rudygalfi** [GoogleChromeLabs/perf-track#6]
Example page: https://perf-track.web.app/react

See attached screenshot: The listing for Not compressed is 11.6%. The pie chart segment proportions don't match. This appears to be because the underlying percent for the "Not compressed" value is inflated.
<img width="1833" alt="Screen Shot 2020-05-29 at 10 12 01" src="https://user-images.githubusercontent.com/3888212/83286676-2e777080-a195-11ea-9d14-2df37c5ee926.png">

**Comment by housseindjirdeh** [comment]
Thanks for spotting this :) 

Fixed!
